/* PUEDE IR ACA LA PAGINACION, y tambien los hooks puede ser */
/* TRATAR DE HACER LOS FETCH APARTES PARA CADA UNO */

/*MODULARIZAR SIEMPRE QUE SE PUEDA*/

/*SIEMPRE VALIDA LOS ERRORES DEL LADO DEL FRONT ANTES QUE DEL BACK*/
/*PARA LOS FORMULARIOS PODEMOS GENERAR UNA PLANTILLA*/

/*COMPRBACION DE ERRORES POR CAMPO EN EL FORMULARIO POR PARTE DEL FRONT*/

/* REAUTILIZAR SLIDE MENU PARA LA PANTALLA DEL CLIENT EN LA INTERFAZ DE CELULAR*/